Fix LoggerBackend.handle_event to handle (ignore) :flush event.
fazibear/airbrakex pull request #18
Opened 2016-12-02 20:25 UTC by jemc

This PR fixes `LoggerBackend.handle_event` to handle (ignore) the `:flush` event.

According to [the official docs for `Logger`](http://elixir-lang.org/docs/stable/logger/Logger.html):

> Once initialized, the handler should be designed to handle events in the following format:

```elixir
{level, group_leader, {Logger, message, timestamp, metadata}} | :flush
```

Not sure if this is a new requirement as of recent versions of Elixir, but at any rate it shouldn't cause any problems with older versions that did not send the `:flush` method, since it is only being ignored.

This PR resolves errors I was seeing when the `:flush` event was not matching any known clause of the `handle_event` function.

2016-12-02 20:48 UTC, fazibear commented
Thanks!

2016-12-04 20:40 UTC, fazibear requested changes

2016-12-04 20:40 UTC, fazibear commented on lib/airbrakex/logger_backend.ex
> +  alias Airbrakex.{LoggerBackend, LoggerParser, Notifier}
CAn you remove LoggerBackend from here ? Is useless. I guess it was a typo.

2016-12-06 17:28 UTC, jemc commented on lib/airbrakex/logger_backend.ex
> +  alias Airbrakex.{LoggerBackend, LoggerParser, Notifier}
Removed in f4ea7a1.

2016-12-06 22:42 UTC, fazibear approved these changes

2016-12-06 22:42 UTC, merged

2016-12-06 22:42 UTC, fazibear commented
Thanks once again!

2016-12-06 23:25 UTC, jemc commented
Thanks for the merge.

Would you mind commenting again on this ticket when the next version has been released to hex.pm?

2016-12-07 11:02 UTC, fazibear commented
Sure, no problem!

2016-12-07 16:02 UTC, fazibear commented
Released!